language: go

go:
  - 1.3
  - 1.4

before_install:
  - git clone https://github.com/retailnext/gocql
  - cd gocql
  - git checkout keyspace_metadata
  - go install
  - go get github.com/stretchr/testify/assert
  - go get github.com/jteeuwen/go-bindata/...
  - go get github.com/relops/csvb
  - go get github.com/cihub/seelog
  - export PATH=$PATH:/home/travis/gopath/bin:/usr/local/cassandra/bin

install:
  - go get -v ./...

script:
  - bash integration.sh
