language: go

go:
  - 1.3
  - 1.4

before_install:
  - mkdir -p $GOPATH/src/github.com/retailnext
  - git clone https://github.com/retailnext/gocql $GOPATH/src/github.com/retailnext/gocql
  - pushd $GOPATH/src/github.com/retailnext/gocql
  - git checkout keyspace_metadata
  - go get .
  - go install
  - popd
  - go get github.com/stretchr/testify/assert
  - go get github.com/jteeuwen/go-bindata/...
  - go get github.com/relops/csvb
  - go get github.com/cihub/seelog
  - export PATH=$PATH:/home/travis/gopath/bin:/usr/local/cassandra/bin

install:
  - go get github.com/jessevdk/go-flags
  - go get speter.net/go/exp/math/dec/inf

script:
  - bash integration.sh
